# Generated by Django 4.1.7 on 2023-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPilotage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('date_time', models.DateTimeField(verbose_name='date published')),
                ('distance_obstacle', models.FloatField()),
                ('distance_altitude', models.FloatField()),
                ('humidite', models.FloatField()),
            ],
        ),
    ]
