# Generated by Django 4.1.7 on 2023-03-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotageApp', '0003_alter_datapilotage_lumiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapilotage',
            old_name='distance_altitude',
            new_name='altitude',
        ),
        migrations.RemoveField(
            model_name='datapilotage',
            name='distance_obstacle',
        ),
    ]
