# Generated by Django 4.1.7 on 2023-04-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotageApp', '0004_rename_distance_altitude_datapilotage_altitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
